 export const Products= [
    {
      "id": 1,
      "name": "Bluetooth Speaker",
      "category": "electronic",
      "description": "Portable wireless speaker with 12-hour battery life and rich stereo sound.",
      "sku": "ELEC-SPK-001",
      "price": 49.99,
      "stock": 150,
      "brand": "SonicWave",
      "image_url": "https://placehold.co/300x300/a855f7/ffffff?text=Speaker"
    },
    {
      "id": 2,
      "name": "Smart LED TV",
      "category": "electronic",
      "description": "55-inch 4K UHD Smart TV with HDR and built-in streaming apps.",
      "sku": "ELEC-TV-002",
      "price": 799.99,
      "stock": 35,
      "brand": "Visualia",
      "image_url": "https://placehold.co/300x300/a855f7/ffffff?text=TV"
    },
    {
      "id": 3,
      "name": "Noise-Cancelling Headphones",
      "category": "electronic",
      "description": "Over-ear headphones with advanced active noise cancellation for immersive audio.",
      "sku": "ELEC-HP-003",
      "price": 199.99,
      "stock": 75,
      "brand": "Acoustix",
      "image_url": "https://placehold.co/300x300/a855f7/ffffff?text=Headphones"
    },
    {
      "id": 4,
      "name": "iPhone 15 Pro",
      "category": "phone and tablet",
      "description": "Latest smartphone model with a triple-camera system and a super retina XDR display.",
      "sku": "PH-IP-004",
      "price": 999.00,
      "stock": 50,
      "brand": "Apple",
      "image_url": "https://placehold.co/300x300/6366f1/ffffff?text=iPhone"
    },
    {
      "id": 5,
      "name": "Samsung Galaxy Tab S9",
      "category": "phone and tablet",
      "description": "Powerful Android tablet with a vibrant AMOLED display and S Pen included.",
      "sku": "PH-TAB-005",
      "price": 799.00,
      "stock": 40,
      "brand": "Samsung",
      "image_url": "https://placehold.co/300x300/6366f1/ffffff?text=Tablet"
    },
    {
      "id": 6,
      "name": "Google Pixel 8",
      "category": "phone and tablet",
      "description": "Smartphone with an advanced AI-powered camera and a secure Titan M2 chip.",
      "sku": "PH-PXL-006",
      "price": 699.00,
      "stock": 60,
      "brand": "Google",
      "image_url": "https://placehold.co/300x300/6366f1/ffffff?text=Pixel"
    },
    {
      "id": 7,
      "name": "Apple iPad Air",
      "category": "phone and tablet",
      "description": "Lightweight and powerful tablet with a stunning Liquid Retina display.",
      "sku": "PH-IPAD-007",
      "price": 599.00,
      "stock": 55,
      "brand": "Apple",
      "image_url": "https://placehold.co/300x300/6366f1/ffffff?text=iPad"
    },
    {
      "id": 8,
      "name": "MacBook Air M2",
      "category": "laptop and accessories",
      "description": "Ultra-thin and powerful laptop with the M2 chip for exceptional performance.",
      "sku": "LAP-MB-008",
      "price": 1199.00,
      "stock": 25,
      "brand": "Apple",
      "image_url": "https://placehold.co/300x300/10b981/ffffff?text=MacBook"
    },
    {
      "id": 9,
      "name": "Dell XPS 15",
      "category": "laptop and accessories",
      "description": "High-performance laptop with a beautiful InfinityEdge display, perfect for creators.",
      "sku": "LAP-DELL-009",
      "price": 1599.00,
      "stock": 18,
      "brand": "Dell",
      "image_url": "https://placehold.co/300x300/10b981/ffffff?text=Dell"
    },
    {
      "id": 10,
      "name": "Wireless Ergonomic Mouse",
      "category": "laptop and accessories",
      "description": "Comfortable and precise wireless mouse designed for long hours of use.",
      "sku": "ACC-MOUSE-010",
      "price": 79.99,
      "stock": 210,
      "brand": "Logitech",
      "image_url": "https://placehold.co/300x300/10b981/ffffff?text=Mouse"
    },
    {
      "id": 11,
      "name": "USB-C Hub",
      "category": "laptop and accessories",
      "description": "Multi-port adapter with HDMI, USB-A, and SD card slots for laptops.",
      "sku": "ACC-HUB-011",
      "price": 39.99,
      "stock": 350,
      "brand": "Anker",
      "image_url": "https://placehold.co/300x300/10b981/ffffff?text=USB+Hub"
    },
    {
      "id": 12,
      "name": "Standing Desk",
      "category": "office and home",
      "description": "Adjustable height desk to switch between sitting and standing for a healthier workday.",
      "sku": "OH-DESK-012",
      "price": 299.99,
      "stock": 80,
      "brand": "FlexiDesk",
      "image_url": "https://placehold.co/300x300/f59e0b/ffffff?text=Standing+Desk"
    },
    {
      "id": 13,
      "name": "Mesh Office Chair",
      "category": "office and home",
      "description": "Ergonomic office chair with breathable mesh back and lumbar support.",
      "sku": "OH-CHAIR-013",
      "price": 189.99,
      "stock": 95,
      "brand": "ErgoPro",
      "image_url": "https://placehold.co/300x300/f59e0b/ffffff?text=Chair"
    },
    {
      "id": 14,
      "name": "Smart Thermostat",
      "category": "office and home",
      "description": "Programmable thermostat that learns your habits to save energy.",
      "sku": "OH-THERMO-014",
      "price": 129.99,
      "stock": 120,
      "brand": "Ecobee",
      "image_url": "https://placehold.co/300x300/f59e0b/ffffff?text=Thermostat"
    },
    {
      "id": 15,
      "name": "Air Purifier",
      "category": "office and home",
      "description": "Hepa filter air purifier to remove allergens and pollutants from your room.",
      "sku": "OH-AIR-015",
      "price": 89.99,
      "stock": 160,
      "brand": "Levoit",
      "image_url": "https://placehold.co/300x300/f59e0b/ffffff?text=Air+Purifier"
    },
    {
      "id": 16,
      "name": "Coffee Maker",
      "category": "kitchen",
      "description": "Programmable drip coffee maker with a 12-cup capacity and a reusable filter.",
      "sku": "KIT-COFFEE-016",
      "price": 59.99,
      "stock": 110,
      "brand": "Keurig",
      "image_url": "https://placehold.co/300x300/ef4444/ffffff?text=Coffee+Maker"
    },
    {
      "id": 17,
      "name": "Toaster Oven",
      "category": "kitchen",
      "description": "Compact countertop toaster oven with bake, broil, and toast functions.",
      "sku": "KIT-TOASTER-017",
      "price": 79.99,
      "stock": 85,
      "brand": "Cuisinart",
      "image_url": "https://placehold.co/300x300/ef4444/ffffff?text=Toaster+Oven"
    },
    {
      "id": 18,
      "name": "Blender",
      "category": "kitchen",
      "description": "High-speed blender with multiple presets for smoothies, shakes, and purees.",
      "sku": "KIT-BLEND-018",
      "price": 89.99,
      "stock": 105,
      "brand": "Vitamix",
      "image_url": "https://placehold.co/300x300/ef4444/ffffff?text=Blender"
    },
    {
      "id": 19,
      "name": "Non-Stick Cookware Set",
      "category": "kitchen",
      "description": "10-piece non-stick cookware set including frying pans and saucepans.",
      "sku": "KIT-COOK-019",
      "price": 149.99,
      "stock": 60,
      "brand": "T-fal",
      "image_url": "https://placehold.co/300x300/ef4444/ffffff?text=Cookware"
    },
    {
      "id": 20,
      "name": "Summer Maxi Dress",
      "category": "fashion",
      "description": "Lightweight, floral maxi dress with a relaxed fit for warm weather.",
      "sku": "FASH-MAXI-020",
      "price": 59.99,
      "stock": 120,
      "brand": "Zara",
      "image_url": "https://placehold.co/300x300/f97316/ffffff?text=Maxi+Dress"
    },
    {
      "id": 21,
      "name": "High-Waisted Jeans",
      "category": "fashion",
      "description": "Classic blue denim jeans with a flattering high-waisted fit.",
      "sku": "FASH-JEANS-021",
      "price": 79.99,
      "stock": 90,
      "brand": "Levi's",
      "image_url": "https://placehold.co/300x300/f97316/ffffff?text=Jeans"
    },
    {
      "id": 22,
      "name": "Leather Tote Bag",
      "category": "fashion",
      "description": "Spacious genuine leather tote bag with a minimalist design.",
      "sku": "FASH-BAG-022",
      "price": 129.99,
      "stock": 45,
      "brand": "Coach",
      "image_url": "https://placehold.co/300x300/f97316/ffffff?text=Tote+Bag"
    },
    {
      "id": 23,
      "name": "Running Sneakers",
      "category": "fashion",
      "description": "Athletic shoes with cushioned support, ideal for running and daily wear.",
      "sku": "FASH-SHOES-023",
      "price": 110.00,
      "stock": 200,
      "brand": "Nike",
      "image_url": "https://placehold.co/300x300/f97316/ffffff?text=Sneakers"
    },
    {
      "id": 24,
      "name": "Men's Slim Fit Blazer",
      "category": "men and women dress",
      "description": "Stylish slim-fit blazer for men, perfect for business casual or special events.",
      "sku": "DRESS-M-BLAZER-024",
      "price": 149.99,
      "stock": 65,
      "brand": "Calvin Klein",
      "image_url": "https://placehold.co/300x300/22c55e/ffffff?text=Blazer"
    },
    {
      "id": 25,
      "name": "Women's A-Line Skirt",
      "category": "men and women dress",
      "description": "Elegant A-line skirt with a pleated design and a midi length.",
      "sku": "DRESS-W-SKIRT-025",
      "price": 69.99,
      "stock": 80,
      "brand": "Banana Republic",
      "image_url": "https://placehold.co/300x300/22c55e/ffffff?text=Skirt"
    },
    {
      "id": 26,
      "name": "Men's Linen Shirt",
      "category": "men and women dress",
      "description": "Breathable and comfortable long-sleeve linen shirt for a relaxed look.",
      "sku": "DRESS-M-SHIRT-026",
      "price": 45.00,
      "stock": 150,
      "brand": "Uniqlo",
      "image_url": "https://placehold.co/300x300/22c55e/ffffff?text=Linen+Shirt"
    },
    {
      "id": 27,
      "name": "Women's Cocktail Dress",
      "category": "men and women dress",
      "description": "Chic cocktail dress with a lace overlay, suitable for formal occasions.",
      "sku": "DRESS-W-DRESS-027",
      "price": 180.00,
      "stock": 30,
      "brand": "BCBGMAXAZRIA",
      "image_url": "https://placehold.co/300x300/22c55e/ffffff?text=Cocktail+Dress"
    },
    {
      "id": 28,
      "name": "Men's Dress Shoes",
      "category": "men and women dress",
      "description": "Classic leather dress shoes for a sharp and professional appearance.",
      "sku": "DRESS-M-SHOES-028",
      "price": 160.00,
      "stock": 50,
      "brand": "Allen Edmonds",
      "image_url": "https://placehold.co/300x300/22c55e/ffffff?text=Dress+Shoes"
    },
    {
      "id": 29,
      "name": "Women's Winter Coat",
      "category": "men and women dress",
      "description": "Warm wool-blend coat with a belted waist and oversized collar.",
      "sku": "DRESS-W-COAT-029",
      "price": 250.00,
      "stock": 25,
      "brand": "J. Crew",
      "image_url": "https://placehold.co/300x300/22c55e/ffffff?text=Winter+Coat"
    },
    {
      "id": 30,
      "name": "Men's Bomber Jacket",
      "category": "men and women dress",
      "description": "Casual bomber jacket with a ribbed collar and cuffs, perfect for transitional weather.",
      "sku": "DRESS-M-JACKET-030",
      "price": 89.00,
      "stock": 70,
      "brand": "H&M",
      "image_url": "https://placehold.co/300x300/22c55e/ffffff?text=Bomber+Jacket"
    }
  ]